name: Deploy Vite App to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Khởi tạo môi trường Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cài đặt các thư viện
        run: npm install --legacy-peer-deps
        working-directory: ./Pisurvivor

      - name: Biên dịch ứng dụng
        run: npm run build
        working-directory: ./Pisurvivor

      - name: Cấu hình GitHub Pages
        uses: actions/configure-pages@v4

      - name: Tải lên sản phẩm đã build
        uses: actions/upload-pages-artifact@v3
        with:
          path: './Pisurvivor/dist'

      - name: Xuất bản lên GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
